### ISSUE TITLE
3 vertices created instead of 1

### ISSUE THREAD

**Issue by deltaray** [sorecords/gridbreaker#2]
I turned on statistics and something seemed odd about the number of vertices. It turns out that it's creating 3 vertices instead of 1 at every corner. The extra two are not attached to any edges or faces.  This of course slows everything down when you have an object with a lot of cuts.

**Comment by sorecords** [comment]
Thank you for the feedback. It will be fixed in the official release version, as well as the calculation speed. I have completely rewritten all the algorithms and am now testing add-on before release.

**Comment by sorecords** [comment]
The new version is released, this issue has been fixed.
